### ISSUE TITLE
mkfsImage error when build hello_dpu

### ISSUE THREAD

**Issue by wujingbang** [gewuek/vitis_ai_custom_platform_v1.2_tmp#1]
Fist of all, appreciate your tutorial ! it is very helpful.
In "Prepare the Network Deployment File", I got following error when building hello_dpu. It seems to be a tiny problem but I have no clue at all...
Environment: Vitis 2020.1, petalinux 2020.1, board: custom ultrascale+mpsoc zu4ev board.

INFO: [v++ 82-1076] Deleting existing - /home/wu/Desktop/petaspace/peta_ai/axu4ev_peta/axu4ev_dpu_pkg/hello_dpu_system/Hardware/package/sd_card/image.ub
INFO: [v++ 82-1011] Creating sd_card directory
/tools/Xilinx/Vitis/2020.1/scripts/vitis/util/mkfsImage.sh: 57: shift: can't shift that many
ERROR: [v++ 82-1081] Cannot generate EXT4 sd_card image
ERROR: [v++ 60-702] Failed to finish packaging
INFO: [v++ 60-1653] Closing dispatch client.
make: *** [package] Error 1
makefile:38: recipe for target 'package' failed

**Comment by gewuek** [comment]
Hi @wujingbang ,

Thanks for reporting this issue.
I haven't met this issue before but when I do a quick research I can see the resolved Xilinx forum post:
https://forums.xilinx.com/t5/Vitis-Acceleration-SDAccel-SDSoC/Cannot-generate-EXT4-sd-card-image-Hardware-build-error-in-Vitis/td-p/1148741
Hope this can help.

**Comment by gewuek** [comment]
Close the issue since there is no further question
