### ISSUE TITLE
Can you refer to this document to build a system on zedboard( zynq7020)

### ISSUE THREAD

**Issue by sunshine411** [gewuek/vitis_ai_custom_platform_v1.2_tmp#2]
Can you refer to this document to build a system on zedboard( zynq7020). 
If OK ,Which parts need to be modified.
Thanks

**Comment by gewuek** [comment]
Hi @sunshine411 ,

I am afraid I can't. The libs for Zynq-7000(Arch32) are not released on Vitis AI 1.2.
So for now you could only use Vivado+DNNDK3.1 to deploy ML solution on Zedboard.

**Comment by gewuek** [comment]
Not avaiable because vai stack for Zynq-7000 is not available.
